config/routes.rb
Rails.application.routes.draw do
  scope "auth" do
    resource :session
    resources :passwords, param: :token
  end

  resources :resources, only: [ :show ]
  resources :orders, only: [ :index, :new, :show, :create ]

  scope "_", as: "admin", admin: true do
    resources :resources, except: [ :index ]
    root "resources#index"
  end

  get "up" => "rails/health#show", as: :rails_health_check

  root "resources#index"
end

app/views/resources/_filter.html.erb
<%= form_with url: root_path, method: :get, local: true, class: "resources-filter-form" do |form| %>
  <fieldset>
    <legend><%= t("form.filters") %></legend>

    <div class="flex fields-wrapper">
      <div class="filter f-price flex align-center">
        <%= form.label :pricing, "#{t("resources.price.label").titleize}:", class: "small" %>
        <%= form.select :pricing,
                    options_for_select(
                      [
                        [t("resources.price.all"), "all"],
                        [t("resources.price.free"), "free"],
                        [t("resources.price.paid"), "paid"],
                      ],
                      selected: "all",
                    ) %>
      </div>
      <div class="filter f-category flex align-center">
        <%= form.label :category_id, "#{t("resources.category").titleize}:", class: "small" %>
        <%= form.collection_select :category_id,
                               Category.all,
                               :id,
                               :name,
                               prompt: "---",
                               selected: params[:category_id] || "---" %>
      </div>
    </div>
  </fieldset>

  <div class="flex controls">
    <button type="reset">
      <%= t("forms.reset") %>
    </button>
    <%= form.submit t("forms.filter") %>
  </div>
<% end %>

app/views/resources/_form.html.erb
<div>
  <%= form_with url: admin_resources_path, model: resource, local: true do |form| %>
    <% if resource.errors.any? %>
      <div class="flash severe small">
        <%= t("forms.invalid") %>
      </div>
    <% end %>

    <div class="my-1">
      <%= form.label :name %>
      <ul class="smaller">
        <% resource.errors.full_messages_for(:name).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.text_field :name %>
    </div>

    <div class="my-1">
      <%= form.label :image %>
      <ul class="smaller">
        <% resource.errors.full_messages_for(:image).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.file_field :image %>
      <small><%= t("resources.image.hint") %></small>
    </div>

    <div class="my-1">
      <%= form.label t("resources.category") %>
      <ul class="smaller">
        <% resource.errors.full_messages_for(:category).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.collection_select :category_id, Category.order(:name), :id, :name %>
    </div>

    <div class="my-1">
      <%= form.label t("resources.price.label") %>
      <ul class="smaller">
        <% resource.errors.full_messages_for(:price).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.number_field :price, min: 0 %>
    </div>

    <div class="my-1">
      <%= form.label :kind %>
      <ul class="smaller">
        <% resource.errors.full_messages_for(:kind).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.select :kind,
                  Resource::VALID_KINDS.map { |kind|
                    [t("resource.kind.#{kind}"), kind]
                  },
                  selected: resource.kind || Resource::VALID_KINDS.first %>
    </div>

    <div class="my-1">
      <%= form.label "URL" %>
      <ul class="smaller">
        <% resource.errors.full_messages_for(:url).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.url_field :url %>
      <small><%= t("resources.url.hint") %></small>
    </div>

    <div class="my-1">
      <%= form.label t("forms.file") %>
      <ul class="smaller">
        <% resource.errors.full_messages_for(:file).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.file_field :file %>
      <small><%= t("resources.file.hint") %></small>
    </div>

    <div class="my-1">
      <%= form.label :description %>
      <ul class="smaller">
        <% resource.errors.full_messages_for(:description).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.text_area :description, rows: 10 %>
    </div>

    <div class="my-1">
      <%= form.submit t("forms.submit") %>
    </div>
  <% end %>
</div>

app/views/resources/_resource.html.erb
<div
  class="resource-item"
  style="background: url('<%= url_for resource.image.variant(:thumb) %>');background-size: cover;"
>
  <a href="<%= resource_url resource %>" class="resource-item_link">
    <div class="resource-item_bg"></div>
    <div class="resource-item_title">
      <%= resource.name %>
    </div>

    <div class="resource-item_info-box">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="0 0 24 24"
      ><path
          fill="currentColor"
          d="M16.813 4.419A1 1 0 0 0 16 4H3a1 1 0 0 0-.813 1.581L6.771 12l-4.585 6.419A1 1 0 0 0 3 20h13a1 1 0 0 0 .813-.419l5-7a1 1 0 0 0 0-1.162zM15.485 18H4.943l3.87-5.419a1 1 0 0 0 0-1.162L4.943 6h10.542l4.286 6z"
        /></svg>
      <span class="resource-item_info">
        <%= resource.category.name.titleize %>
      </span>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="0 0 24 24"
        style="margin-left: auto"
      ><path
          fill="currentColor"
          d="M21 4H3a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h18a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1m-1 11a3 3 0 0 0-3 3H7a3 3 0 0 0-3-3V9a3 3 0 0 0 3-3h10a3 3 0 0 0 3 3z"
        /><path
          fill="currentColor"
          d="M12 8c-2.206 0-4 1.794-4 4s1.794 4 4 4s4-1.794 4-4s-1.794-4-4-4m0 6c-1.103 0-2-.897-2-2s.897-2 2-2s2 .897 2 2s-.897 2-2 2"
        /></svg>
      <span class="resource-item_info">
        <% if resource.price > 0 %>
          <%= "#{resource.price} XOF" %>
        <% else %>
          <%= t("resources.price.free") %>
        <% end %>
      </span>
    </div>
  </a>
</div>

app/views/resources/edit.html.erb
<h2><%= "#{t("resources.edit")} '#{@resource.name}'" %></h2>
<div>
  <%= form_with url: admin_resource_path(@resource), model: @resource, local: true do |form| %>
    <% if @resource.errors.any? %>
      <div class="flash severe small">
        <%= t("forms.invalid") %>
      </div>
    <% end %>

    <div class="my-1">
      <%= form.label :name %>
      <ul class="smaller">
        <% @resource.errors.full_messages_for(:name).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.text_field :name %>
    </div>

    <div class="my-1">
      <%= form.label :image %>
      <ul class="smaller">
        <% @resource.errors.full_messages_for(:image).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.file_field :image %>
      <small><%= t("resources.image.hint") %></small>
    </div>

    <div class="my-1">
      <%= form.label t("resources.category") %>
      <ul class="smaller">
        <% @resource.errors.full_messages_for(:category).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.collection_select :category_id, Category.order(:name), :id, :name %>
    </div>

    <div class="my-1">
      <%= form.label t("resources.price.label") %>
      <ul class="smaller">
        <% @resource.errors.full_messages_for(:price).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.number_field :price, min: 0 %>
    </div>

    <div class="my-1">
      <%= form.label :kind %>
      <ul class="smaller">
        <% @resource.errors.full_messages_for(:kind).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.select :kind,
                  Resource::VALID_KINDS.map { |kind|
                    [t("resource.kind.#{kind}"), kind]
                  },
                  selected: @resource.kind || Resource::VALID_KINDS.first %>
    </div>

    <div class="my-1">
      <%= form.label "URL" %>
      <ul class="smaller">
        <% @resource.errors.full_messages_for(:url).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.url_field :url %>
      <small><%= t("resources.url.hint") %></small>
    </div>

    <div class="my-1">
      <%= form.label t("forms.file") %>
      <ul class="smaller">
        <% @resource.errors.full_messages_for(:file).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.file_field :file %>
      <small><%= t("resources.file.hint") %></small>
    </div>

    <div class="my-1">
      <%= form.label :description %>
      <ul class="smaller">
        <% @resource.errors.full_messages_for(:description).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.text_area :description, rows: 10 %>
    </div>

    <div class="my-1">
      <%= form.submit t("forms.submit") %>
    </div>
  <% end %>
</div>

app/views/resources/index.html.erb
<%= tag.div(flash[:alert], class: "flash severe") if flash[:alert] %>
<%= tag.div(flash[:notice], class: "flash success") if flash[:notice] %>

<h2 class="mt-1.5"><%= t("models.resources") %></h2>
<% if staff? && params[:admin] %>
  <div class="my-.5">
    <%= link_to t("resources.new"), new_admin_resource_path(@resource) %>
  </div>
<% end %>
<!-- Adapted from https://codepen.io/wikyware-net/pen/dyKPRxQ -->
<%= render "filter" %>
<div class="resources-container">
  <%= render @resources %>
</div>
<%= will_paginate @resources %>

app/views/resources/new.html.erb
<h2><%= t("resources.new") %></h2>
<div>
  <%= form_with url: admin_resources_path, model: @resource, local: true do |form| %>
    <% if @resource.errors.any? %>
      <div class="flash severe small">
        <%= t("forms.invalid") %>
      </div>
    <% end %>

    <div class="my-1">
      <%= form.label :name %>
      <ul class="smaller">
        <% @resource.errors.full_messages_for(:name).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.text_field :name %>
    </div>

    <div class="my-1">
      <%= form.label :image %>
      <ul class="smaller">
        <% @resource.errors.full_messages_for(:image).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.file_field :image, accept: ".jpg,.jpeg,.png" %>
      <small><%= t("resources.image.hint") %></small>
    </div>

    <div class="my-1">
      <%= form.label t("resources.category") %>
      <ul class="smaller">
        <% @resource.errors.full_messages_for(:category).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.collection_select :category_id, Category.order(:name), :id, :name %>
    </div>

    <div class="my-1">
      <%= form.label t("resources.price.label") %>
      <ul class="smaller">
        <% @resource.errors.full_messages_for(:price).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.number_field :price, min: 0 %>
    </div>

    <div class="my-1">
      <%= form.label :kind %>
      <ul class="smaller">
        <% @resource.errors.full_messages_for(:kind).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.select :kind,
                  Resource::VALID_KINDS.map { |kind|
                    [t("resource.kind.#{kind}"), kind]
                  },
                  selected: @resource.kind || Resource::VALID_KINDS.first %>
    </div>

    <div class="my-1">
      <%= form.label "URL" %>
      <ul class="smaller">
        <% @resource.errors.full_messages_for(:url).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.url_field :url %>
      <small><%= t("resources.url.hint") %></small>
    </div>

    <div class="my-1">
      <%= form.label t("forms.file") %>
      <ul class="smaller">
        <% @resource.errors.full_messages_for(:file).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.file_field :file, accept: ".pdf,.txt" %>
      <small><%= t("resources.file.hint") %></small>
    </div>

    <div class="my-1">
      <%= form.label :description %>
      <ul class="smaller">
        <% @resource.errors.full_messages_for(:description).each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
      <%= form.text_area :description, rows: 10 %>
    </div>

    <div class="my-1">
      <%= form.submit t("forms.submit") %>
    </div>
  <% end %>
</div>

app/views/resources/show.html.erb
<%= tag.div(flash[:alert], class: "flash severe") if flash[:alert] %>
<%= tag.div(flash[:notice], class: "flash success") if flash[:notice] %>

<h2><%= @resource.name %></h2>
<% if staff? %>
  <div class="my-.5">
    <%= link_to t("resources.edit"), edit_admin_resource_path(@resource) %>

    <%= link_to t("resources.destroy.label"),
    admin_resource_path(@resource),
    data: {
      turbo_method: :delete,
      turbo_confirm: t("resources.destroy.confirm"),
    } %>
  </div>
<% end %>
<picture>
  <!-- Small screens (mobile) -->
  <source
    media="(max-width: 600px)"
    srcset="<%= url_for  @resource.image.variant(:mobile) %>"
  >
  <!-- Medium screens (tablet) -->
  <source
    media="(max-width: 1024px)"
    srcset="<%= url_for  @resource.image.variant(:tablet) %>"
  >
  <!-- Standard desktop screens (up to 1920px) -->
  <source
    media="(max-width: 1920px)"
    srcset="<%= url_for  @resource.image.variant(:desktop) %>"
  >
  <!-- Default (original image) -->
  <%= image_tag @resource.image, style: "width: 100%; max-width: 100%; height: auto;" %>
</picture>
<% unless staff? %>
<%=  render "orders/form", order: @order  %>
<%  end %>
<div class="my-2">
  <h3>Description</h3>
  <% @resource.description.split("\n").each do |par| %>
    <p><%= par %></p>
  <% end %>
</div>
<div>
  <h3><%= t("resources.similar") %></h3>

  <div class="resources-container">
    <%= render Resource
      .order(created_at: :desc)
      .where(category: @resource.category)
      .where.not(id: @resource.id)
      .limit(3) %>
  </div>
  <%= link_to t("resources.view_all"), root_path, class: "ml-1" %>
</div>