config/routes.rb
Rails.application.routes.draw do
  scope "auth" do
    resource :session
    resources :passwords, param: :token
  end

  resources :resources, only: [ :show ]
  resources :orders, only: [ :index, :new, :show, :create ]

  scope "_", as: "admin", admin: true do
    resources :resources, except: [ :index ]
    root "resources#index"
  end

  get "up" => "rails/health#show", as: :rails_health_check

  root "resources#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<footer>
  <span>&copy; Copyright 2024 💫 Irawo
    <sup class="accent">mini</sup></span>
  &bull;
  <span>
    <%= t("footer.attribution") %>
    <a href="https://tobihans.space" target="_blank">Hans Tognon</a>
  </span>
</footer>

app/views/application/_header.html.erb
<header>
  <h1>
    <%= link_to "💫 Irawo", root_path, class: "logo bold" %>
    <sup class="accent">
      <span class="small">Mini</span>
      <% if params[:admin].eql? true %>
        <sub class="smaller active">Staff</sub>
      <% end %>
    </sup>
  </h1>
  <menu class="desktop-menu" style="margin-left: 1.25rem; flex-grow: 1;">
    <li class="<%= 'selected' if controller_name == "resources" %>">
      <%= link_to t("models.resources"), root_path %>

      <% if staff? %>
        <menu>
          <li>
            <%= link_to t("resources.new"), new_admin_resource_path(@resource) %>
          </li>
        </menu>
      <% end %>
    </li>
    <% unless staff? %>
    <li class="<%=  'selected' if controller_name == "history"  %>">
      <%=  link_to t("header.history "), orders_path  %>
    </li>
    <%  end %>
    <% if authenticated? %>
      <li style="margin-left: auto;">
        <%= current_user.email_address %>
        <menu>
          <li>
            <%= link_to t("auth.signout"), session_path, data: { turbo_method: :delete } %>
          </li>
        </menu>
      </li>
    <% else %>
      <li style="margin-left: auto;">
        <%= link_to t("auth.signin"), new_session_path, class: "px-.75 py-.5" %>
      </li>
    <% end %>
  </menu>
  <menu class="mobile-menu">
    <li>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="0 0 24 24"
      ><path fill="currentColor" d="M4 6h16v2H4zm0 5h16v2H4zm0 5h16v2H4z"/></svg>
      <span>Menu</span>
      <menu>
        <li class="<%= 'selected' if controller_name == "resources" %>">
          <%= link_to t("models.resources"), root_path %>
        </li>
        <% if staff? %>
          <li class="<%= 'selected' if controller_name == "history" %>">
            <%= link_to t("resources.new"), new_admin_resource_path(@resource) %>
          </li>
        <% end %>
        <% unless staff? %>
        <li class="<%=  'selected' if controller_name == "history"  %>">
          <%=  link_to t("header.history "), orders_path  %>
        </li>
        <%  end %>
        <% if authenticated? %>
          <li class="disabled">
            <%= current_user.email_address %>
          </li>
          <li>
            <%= link_to t("auth.signout"), session_path, data: { turbo_method: :delete } %>
          </li>
        <% else %>
          <li>
            <%= link_to t("auth.signin"), new_session_path %>
          </li>
        <% end %>
      </menu>
    </li>
  </menu>
</header>